### ISSUE TITLE
Please add a license to this project!

### ISSUE THREAD

**Issue by ernestoongaro** [dpguthrie/dbt-sl-streamlit#6]
I would recommend [The Unlicense](https://choosealicense.com/licenses/unlicense/) as it is ridiculously open, and protects you from any warranty claims. that said, I'm not a lawyer but I do some lawyering on the side, fully trained by @nickyspitz who is also not a lawyer.

**Comment by dpguthrie** [comment]
@ernestoongaro [I will always](https://github.com/dpguthrie/dbt-sl-streamlit/blob/main/LICENSE) accept legal advice from you!

**Comment by nickyspitz** [comment]
@ernestoongaro and @dpguthrie - it is an honour to welcome you both to the
cowboy lawyering guild. I look forward to seeing many more ad-hoc and
reasonable rulings from you both!
